language: java
jdk:
- openjdk8

install: true

script: gradle :api:build

before_install:
- gradle :api:clean

branches:
  only:
  - master

cache:
  directories:
  - '$HOME/.gradle'

after_success:
- gradle :api:clean jacocoTestReport coveralls