language: java
jdk:
- openjdk8

install: true

script: gradle :api:build

before_install:
- gradle :api:clean

branches:
    only:
    - master

cache:
    directories:
    - '$HOME/.gradle'

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
