spring:
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
      naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 50



server:
    port: 8080

logging:
  path: /tmp/log
  level:
    org:
      hibernate:
        type: trace

